    name: CI/CD - Build and Push Docker Image

    # Run this workflow on every push to the 'main' branch
    on:
      push:
        branches: [ "main" ]

    # This allows the workflow to write to GitHub Packages (GHCR)
    permissions:
      contents: read
      packages: write

    jobs:
      build-and-push-image:
        runs-on: ubuntu-latest # Use a standard Linux runner
        
        steps:
          - name: Check out the repository
            uses: actions/checkout@v4

          - name: Log in to GitHub Container Registry (GHCR)
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              # 'github.repository_owner' is a built-in variable for your username/org
              username: ${{ github.repository_owner }}
              # We use the secret we created
              password: ${{ secrets.GHCR_PAT }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .  # Use the root of the repo as the build context
              push: true # We want to push the image
              tags: |
                ghcr.io/${{ github.repository_owner }}/devops-ids-lab:latest
                ghcr.io/${{ github.repository_owner }}/devops-ids-lab:${{ github.sha }}
              # This builds and tags the image as 'latest' and also with the unique commit SHA
    
